@base = http://localhost:5000

### Docs: https://github.com/Huachao/vscode-restclient

### List todos
get {{base}}/todo/

### get One
get {{base}}/todo/9999

### delete One
delete {{base}}/todo/4

### POST data
post {{base}}/todo/
Content-Type: application/json

{
    "name": "finish API",
    "done": 0
}


### PUT data (update)
put {{base}}/todo/3
Content-Type: application/json

{
    "name": "Finish API",
    "done": 1
}
